### ISSUE TITLE
Remove unused stuff

### ISSUE THREAD

**Issue by byme8** [rngk2/MoneyKeeperBackend#17]
https://github.com/rngk2/MoneyKeeperBackend/blob/50be6e8caa6c9cb851ba08f0bd26f864c37bb78a/DAL/Utils/SqlQueryGenerator.cs#L9

**Comment by rngk2** [comment]
https://github.com/rngk2/MoneyKeeperBackend/commit/a00c5b0ba00840a312d06af1e89080237d5a55ec
